version: "3.9"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=online_household_product_order
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products_service
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    volumes:
      - ./products:/app
      - products_node_modules:/app/node_modules
    env_file:
      - ./products/.env

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping_service
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    volumes:
      - ./shopping:/app
      - shopping_node_modules:/app/node_modules
    env_file:
      - ./shopping/.env

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer_service
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    volumes:
      - ./customer:/app
      - customer_node_modules:/app/node_modules
    env_file:
      - ./customer/.env

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 80:80

volumes:
  mongodb_data:
    driver: local
  products_node_modules:
    driver: local
  shopping_node_modules:
    driver: local
  customer_node_modules:
    driver: local
